-- lua/plugins/treesitter.lua
return {
  {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate", -- Automatically update parsers

    opts = {
      ensure_installed = {
        "astro",
        "bash",
        "bibtex",
        "c",
        "cmake",
        "comment",
        "cpp",
        "css",
        "c_sharp",
        "dart",
        "diff",
        "dockerfile",
        "fennel",
        "fish",
        "git_config",
        "git_rebase",
        "gitcommit",
        "gitignore",
        "go",
        "gomod",
        "gosum",
        "gowork",
        "graphql",
        "html",
        "htmldjango",
        "ini",
        "java",
        "javascript",
        "jinja",
        "jsdoc",
        "json",
        "jsonc",
        "kotlin",
        "latex",
        "lua",
        "luadoc",
        "luap",
        "make",
        "markdown",
        "markdown_inline",
        "meson",
        "ninja",
        "php",
        "php_only",
        "phpdoc",
        "python",
        "query",
        "regex",
        "rust",
        "scfg",
        "scheme",
        "scss",
        "ssh_config",
        "sql",
        "svelte",
        "toml",
        "tsx",
        "typescript",
        "udev",
        "v",
        "vim",
        "vimdoc",
        "vue",
        "yaml",
        "zig",
      },

      highlight = { enable = true },

      -- You can add more options here later (indent, incremental_selection, textobjects, etc.)
      -- indent = { enable = true },
      -- incremental_selection = { enable = true },
    },

    config = function(_, opts)
      require("nvim-treesitter.configs").setup(opts)
    end,
  },
}
