
file-picker-cmd = fzf --multi --query=%s file-picker-cmd = yazi --choose-files=%f


[Proton]
source         = notmuch://~/.local/share/mail
outgoing       = smtp://peter.colebourne%40protonmail.com:fBGx503bpaZSTJRWiD0Kpw@127.0.0.1:1025
default        = INBOX
from           = Pete Colebourne <p.colebourne@protonmail.com>
copy-to        = proton/Sent
archive        = proton/Archive
trash          = proton/Trash
maildir-store  = ~/.local/share/mail/
check-mail-cmd = mbsync -q proton && notmuch new
check-mail     = 5m
check-mail-timeout = 20s
query-map      = ~/.config/aerc/Proton.qmap
folder-map     = ~/.config/aerc/proton.map
folders        = Inbox,proton/Archive,proton/Inbox,INBOX,proton/Sent,proton/Spam,proton/Trash
folders-sort   = INBOX,Inbox,proton/Sent,proton/Archive


[GMail]
source         = notmuch://~/.local/share/mail
outgoing       = smtps://peter.colebourne%40gmail.com:zjnx%20jbcn%20ckcs%20riya@smtp.gmail.com:465
default        = INBOX
from           = Pete Colebourne <peter.colebourne@gmail.com>
copy-to        = gmail/Sent
archive        = gmail/Archive
trash          = gmail/Bin
maildir-store  = ~/.local/share/mail/
check-mail-cmd = mbsync -q gmail
check-mail     = 1h
check-mail-timeout = 20s
query-map      = ~/.config/aerc/gmail.qmap
folders        = INBOX,gmail/Sent,gmail/Inbox,gmail/Archive,gmail/Junk,gmail/Bin

